
package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Tutorial4WebService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/TutorialFour/Tutorial4WebService?wsdl")
public class Tutorial4WebService_Service
    extends Service
{

    private final static URL TUTORIAL4WEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException TUTORIAL4WEBSERVICE_EXCEPTION;
    private final static QName TUTORIAL4WEBSERVICE_QNAME = new QName("http://server/", "Tutorial4WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TutorialFour/Tutorial4WebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TUTORIAL4WEBSERVICE_WSDL_LOCATION = url;
        TUTORIAL4WEBSERVICE_EXCEPTION = e;
    }

    public Tutorial4WebService_Service() {
        super(__getWsdlLocation(), TUTORIAL4WEBSERVICE_QNAME);
    }

    public Tutorial4WebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TUTORIAL4WEBSERVICE_QNAME, features);
    }

    public Tutorial4WebService_Service(URL wsdlLocation) {
        super(wsdlLocation, TUTORIAL4WEBSERVICE_QNAME);
    }

    public Tutorial4WebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TUTORIAL4WEBSERVICE_QNAME, features);
    }

    public Tutorial4WebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Tutorial4WebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Tutorial4WebService
     */
    @WebEndpoint(name = "Tutorial4WebServicePort")
    public Tutorial4WebService getTutorial4WebServicePort() {
        return super.getPort(new QName("http://server/", "Tutorial4WebServicePort"), Tutorial4WebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Tutorial4WebService
     */
    @WebEndpoint(name = "Tutorial4WebServicePort")
    public Tutorial4WebService getTutorial4WebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "Tutorial4WebServicePort"), Tutorial4WebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TUTORIAL4WEBSERVICE_EXCEPTION!= null) {
            throw TUTORIAL4WEBSERVICE_EXCEPTION;
        }
        return TUTORIAL4WEBSERVICE_WSDL_LOCATION;
    }

}
